CREATE DATABASE db_locadora_filme_ds2m_25_2;

USE db_locadora_filme_ds2m_25_2;

CREATE TABLE tb_filme (
	
	id INT PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(100) NOT NULL,
	sinopse TEXT NULL,
	data_lancamento DATE NULL,
	duracao TIME NOT NULL,
	orcamento DECIMAL(10, 2) NOT NULL,
	trailer VARCHAR(255) NULL,
	capa VARCHAR(255) NOT NULL

);

CREATE TABLE tb_cargo (
	
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL
	
);

CREATE TABLE tb_profissional(
	
	id INT PRIMARY KEY AUTO_INCREMENT,
	idade INT NULL,
	foto VARCHAR(255) NULL,
	biografia TEXT NULL,
	id_cargo INT NOT NULL,
	
	CONSTRAINT FK_CARGO_PROFISSIONAL
	FOREIGN KEY (id_cargo)
	REFERENCES tb_cargo(id)
	
);

CREATE TABLE tb_equipe_tecnica(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_filme INT NOT NULL,
	
	CONSTRAINT FK_FILME_EQUIPE_TECNICA
	FOREIGN KEY (id_filme)
	REFERENCES tb_filme(id)

);

CREATE TABLE tb_profissional_cargo(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_profissional INT NOT NULL,
	id_cargo INT NOT NULL,
	
	CONSTRAINT FK_PROFISSIONAL_PROFISSIONAL_CARGO
	FOREIGN KEY (id_profissional)
	REFERENCES tb_profissional(id),
	
	CONSTRAINT FK_CARGO_PROFISSIONAL_CARGOs
	FOREIGN KEY (id_cargo)
	REFERENCES tb_cargo(id)

);

CREATE TABLE tb_profissional_equipe(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_profissional INT NOT NULL,
	id_equipe_tecnica INT NOT NULL,
	
	CONSTRAINT FK_PROFISSIONAL_PROFISSIONAL_EQUIPE
	FOREIGN KEY (id_profissional)
	REFERENCES tb_profissional(id),
	
	CONSTRAINT FK_EQUIPE_TECNICA_EQUIPE_TECNICA
	FOREIGN KEY (id_equipe_tecnica)
	REFERENCES tb_equipe_tecnica(id)

);

CREATE TABLE tb_genero(

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL

);

CREATE TABLE tb_filme_genero(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_genero INT NOT NULL,
	id_filme INT NOT NULL,
	
	CONSTRAINT FK_GENERO_FILME_GENERO
	FOREIGN KEY (id_genero)
	REFERENCES tb_genero(id),
	
	CONSTRAINT FK_FILME_FILME_GENERO
	FOREIGN KEY (id_filme)
	REFERENCES tb_filme(id)
	
);

CREATE TABLE tb_distribuidora(

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL

);

CREATE TABLE tb_filme_distribuidora(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_distribuidora INT PRIMARY NOT NULL,
	id_filme INT PRIMARY NOT NULL,
	
	CONSTRAINT FK_DISTRIBUIDORA_FILME_DISTRIBUIDORA
	FOREIGN KEY (id_distribuidora)
	REFERENCES tb_distribuidora(id),
	
	CONSTRAINT FK_FILME_FILME_DISTRIBUIDORA
	FOREIGN KEY (id_filme)
	REFERENCES tb_filme(id)

);

CREATE TABLE tb_estudio(

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL

);

CREATE TABLE tb_filme_estudio(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_estudio INT NOT NULL,
	id_filme INT NOT NULL,
	
	CONSTRAINT FK_ESTUDIO_FILME_ESTUDIO
	FOREIGN KEY (id_estudio)
	REFERENCES tb_estudio(id),
	
	CONSTRAINT FK_FILME_FILME_ESTUDIO
	FOREIGN KEY (id_filme)
	REFERENCES tb_filme(id)

);

CREATE TABLE tb_ator(

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	idade INT NULL,
	foto VARCHAR(255) NULL

);

CREATE TABLE tb_papel (

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL

);

CREATE TABLE tb_personagem (

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	descricao TEXT NULL,
	foto VARCHAR(255) NULL,
	id_papel INT NOT NULL,
	
	CONSTRAINT FK_PAPEL_PERSONAGEM
	FOREIGN KEY (id_papel)
	REFERENCES tb_papel(id)
	
);

CREATE TABLE tb_ator_personagem(
	
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_ator INT NOT NULL,
	id_personagem INT NOT NULL,
	
	CONSTRAINT FK_ATOR_ATOR_PERSONAGEM
	FOREIGN KEY (id_ator)
	REFERENCES tb_ator(id),
	
	CONSTRAINT FK_PERSONAGEM_ATOR_PERSONAGEM
	FOREIGN KEY (id_personagem)
	REFERENCES tb_personagem(id)

);

CREATE TABLE tb_idioma(

	id INT PRIMARY KEY AUTO_INCREMENT,
	sigla_idioma VARCHAR(5) NOT NULL

);

CREATE TABLE tb_dublador(

	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	foto VARCHAR(255) NULL

);

CREATE TABLE tb_dublador_idioma(

	id INT PRIMARY KEY AUTO_INCREMENT,
	id_dublador INT NOT NULL,
	id_idioma INT NOT NULL,
	
	CONSTRAINT FK_DUBLADOR_DUBLADOR_IDIOMA
	FOREIGN KEY (id_dublador)
	REFERENCES tb_dublador(id),
	
	CONSTRAINT FK_IDIOMA_DUBLADOR_IDIOMA
	FOREIGN KEY (id_idioma)
	REFERENCES tb_idioma(id)

);
